### ISSUE TITLE
Application raised an exception 

### ISSUE THREAD

**Issue by Gurshan26** [Mayconpm/CS50x_2021#3] opened 2021-06-06 14:22 UTC
Hey Mayconpm,
Firstly thank you so so much for the code. It’s really well written and has helped me a lot. However, I am getting this error message with the exact same code. 

The terminal says, “application raised an exception” in red which doesn’t allow the program to compile. 

Could you please tell me how I could possibly resolve this as I’ve ragged  my brain over this since the past 3 days but haven’t come to a definite output…it’ll be really kind of you:) 

Thankyou so much again for the brilliant code!! 

![3BA0AB3C-8677-4200-B290-EF5E45DE0E53](https://user-images.githubusercontent.com/84992481/120927923-3818aa00-c700-11eb-88c1-d75228a5c3c8.jpeg)

**Comment by Mayconpm** [comment] 2021-06-07 15:39
Duplicate of #1 

Given the complexity of pset9, the solution requires more than one table, hence this error. Unfortunately, as explained in #1 this code cannot be used directly as it will not score 100%. How to give the solution goes against the course's honesty policy, what I recommend is to try to develop your own code and use this only to clarify doubts.

**Closed as completed by Mayconpm** 2021-06-07 15:39 UTC
Labels: duplicate, wontfix

**Comment by Gurshan26** [comment] 2021-06-14 17:34
I, in no way want to go against the course’s academic honesty sir. But I’m completely blank as to where exactly I’m going wrong…where do I need to improve? Which part? Why this error? I’ve tried ragging my brain since the day u sent this reply but I’m still stuck on the same error. Please please help sir. I’ll be really grateful

**Comment by Mayconpm** [comment] 2021-06-18 20:20
This error is raised because the .db file provided by the Havard staff has fewer tables than the code demands. 
That's why I encourage everyone to create their own code as this code will not work if used directly.

**Comment by RianMarques26** [comment] 2021-12-27 05:39
Hey Mayconpm, hope all is well. Could you please help me with this issues on Pset9 Finance?

 When I put my API_Key and run flask, I get these errors that I haven't seen before and don't know how to fix:

Traceback (most recent call last): 
File "/usr/local/lib/python3.9/site-packages/cachelib/file.py", line 219, in delete os.remove(self._get_filename(key)) 
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmplxzjvek9/f65da5cfc2b86410e5c673fb6ba2227e'

I have been stuck for the past 2 hours trying to fix this. I tried to ignore them and start the problem set by doing the register part and when I test it I get more issues (AttributeError: 'str' object has no attribute 'get') as you can see. Please help, thanks!
